name: Deploy Angular

on:
  push:
    branches:
      - buscadorRecetas
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.20.0'
      - name: Instalar dependencias
        run:
          npm install || true

      - name: Mostrar logs de npm-debug
        if: failure()
        run:
          type npm-debug.log
      # 3️⃣ Ver estructura del repo (DEBUG)
      - name: Ver estructura del repo
        run: |
          pwd
          ls -la

      # 4️⃣ Instalar dependencias Angular
      - name: Instalar dependencias
        run: npm install

      # 5️⃣ Build Angular producción
      - name: Build Angular
        run: npm run build -- --configuration production

      # 6️⃣ Verificar build generado (DEBUG)
      - name: Ver archivos generados
        run: |
          echo "Contenido de dist:"
          ls -R dist

      # 7️⃣ Verificar secrets (DEBUG)
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SERVER_PASS }}" ]; then
            echo "❌ SERVER_PASS está vacío"
            exit 1
          else
            echo "✅ SERVER_PASS detectado"
          fi

      # 6️⃣ Comprimir build Angular en ZIP
      - name: Crear ZIP del build
        run: |
          cd dist
          zip -r frontend.zip mi-app
          mv frontend.zip ..

      # 7️⃣ Verificar ZIP creado
      - name: Verificar ZIP
        run: |
          ls -lh frontend.zip

      # 8️⃣ Verificar secrets
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.SERVER_PASS }}" ]; then
            echo "❌ SERVER_PASS está vacío"
            exit 1
          else
            echo "✅ SERVER_PASS detectado"
          fi

      # 9️⃣ Enviar ZIP al servidor Windows (IIS)
      - name: Deploy ZIP a IIS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: Administrator
          password: ${{ secrets.SERVER_PASS }}
          port: '22'
          source: "frontend.zip"
          target: ${{ secrets.SERVER_PATH_FRONTEND }}



